version: "3.3"
services:
  verif-server:
    image: "registry.reo.ru/rt/verif-server"
    container_name: verif-server
    build: .
    ports:
      - "8090:8080"
    environment:
      DDL_AUTO: ${DDL_AUTO}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      IDENTITY_URL: ${IDENTITY_URL}
      DADATA_TOKEN: ${DADATA_TOKEN}
      API_URL: ${API_URL}

    volumes:
     - /home/user/verif-server:/opt/verification-photos
    networks:
      - verif-server_net 
networks:
  verif-server_net: 
